name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {packages: write, contents: read}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with: {registry: ghcr.io, username: ${{ github.actor }}, password: ${{ secrets.GITHUB_TOKEN }}}
      - uses: docker/build-push-action@v4
        with: {context: ., push: true, tags: ghcr.io/echoping07/business-gemini-pool:latest}
